---

# Presente na versão 2.1 - Use docker caso contrário
- name: Instalação de Container "web" com o Puppet-Agent no Docker
  docker_container:
    name: web
    hostname: web
    etc_hosts:
      devops.dexter.com.br: 192.168.200.100
    ports:
      - "80:80"
    image: deploy
    command:
      - /bin/bash
      - puppet agent --enable
      - puppet agent -t --server devops.dexter.com.br
      - service apache2 status
    tty: yes
    state: started
