---
# tasks file for docker-registry
- name: Instalação das dependências do Docker Registry Admin
  apt:
    name: {{ package }}
    state: latest

- name: Criação da configuração do Docker Registry Admin
  copy:
    src: jensible.conf
    dest: /etc/apache2/sites-available/jensible.conf
    owner: root
    group: root
    mode: 644

- name: Carregar a configuração do Docker Registry Admin
  command: a2ensite jensible.conf

- name: Ativar o mod_wsgi
  command: a2enmod wsgi

- name: Copiar os arquivos do Docker Registry Admin
  copy:
    src: jensible/*
    dest: /var/www/html
    owner: www-data
    group: www-data

- name: Instalar todas as dependências do projeto
  pip:
    requirements: /var/www/html/requirements.txt

- name: Reboot Apache2 Service - Systemd way
  systemd:
    daemon_reload: yes
    state: restarted
    enabled: yes
    name: 'apache2'
  ignore_errors: yes

- name: Reboot Apache2 Service - Upstart/System V way
  service:
    name: 'apache2'
    state: restarted
    enabled: yes
  ignore_errors: yes
