---
# tasks file for puppet
- name: Instalacao dos pacotes e dependencias do Puppet
  apt:
    name: {{ packages }}
    update_cache: yes
    state: present

- name: Download e instalação do Puppet
  apt:
    deb: https://apt.puppetlabs.com/puppetlabs-release-pc1-{{ ansible_distribution_release }}.deb
    state: present
